name: cd

on:
    push:
        branches: [main]

jobs:
    Deploy:
     name: Deploy
     runs-on: ubuntu-latest

     steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: gosec
        run: $(go env GOPATH)/bin/gosec ./...

      - name: build
        run: ./scripts/buildprod.sh

      - name: Force Success
        run: (exit 0)
